#!/usr/bin/env bash
# shellcheck disable=SC1090,SC1091

# macOS の警告文を表示しない
export BASH_SILENCE_DEPRECATION_WARNING=1

: "Configure Histroy" && {
    # 複数行にまたがったコマンドを1行のヒストリに保存する
    shopt -s cmdhist
    # ヒストリに同じコマンドを連続して保存しない
    export HISTCONTROL=ignoredups:erasedups
    # ヒストリに保存するコマンド数を増やす
    export HISTSIZE=100000
    # ヒストリファイルに保存するコマンド数を増やす
    export HISTFILESIZE=100000

    # ヒストリファイルに保存する際に重複を削除する
    shopt -u histappend
    export PROMPT_COMMAND="history -a; history -c; history -r"
}

: "Setup Homebrew" && {
    test -x "/opt/homebrew/bin/brew" && {
        # Homebrew の環境変数を設定する
        eval "$(/opt/homebrew/bin/brew shellenv)"

        # upgrade や install の際の自動アップデートを無効にする
        export HOMEBREW_NO_AUTO_UPDATE=1

        # asdf の環境変数を設定する
        ASDF_PREFIX=$(brew --prefix asdf)
        test -d "$ASDF_PREFIX" && . "$ASDF_PREFIX/libexec/asdf.sh"

        # mise の環境変数を設定する
        ASDF_PREFIX=$(brew --prefix mise)
        test -d "$ASDF_PREFIX" && eval "$(mise activate bash)"

        # coreutils の libexec/gnubin を PATH に追加する
        COREUTILS_PREFIX=$(brew --prefix coreutils)
        test -d "$COREUTILS_PREFIX" && export PATH="$COREUTILS_PREFIX/libexec/gnubin:$PATH"
    }
}

: "Configure PATH" && {
    # type /opt/homebrew/opt/socket_vmnet/bin/socket_vmnet && PATH="/opt/homebrew/opt/socket_vmnet/bin:$PATH" # socket_vmnet のパスを追加する。lima の `--network="lima:shared` で使用する。
    PATH="$HOME/bin:$PATH" # 自作スクリプトのパスを追加する
    PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
    export PATH
}

: "XDG_BASE_DIRS" && {
    # see. https://wiki.archlinux.jp/index.php/XDG_Base_Directory
    export XDG_CONFIG_HOME="$HOME/.config"
    export XDG_CACHE_HOME="$HOME/.cache"
    export XDG_DATA_HOME="$HOME/.local/share"
    export XDG_STATE_HOME="$HOME/.local/state"
    export XDG_DATA_DIRS="/usr/local/share:/usr/share"
    export XDG_CONFIG_DIRS="/etc/xdg"
}

: "Setup Environments" && {
    export INPUTRC="$XDG_CONFIG_HOME"/readline/inputrc
    type nvim &>/dev/null && export EDITOR=nvim || export EDITOR=vim
}

: "Startup" && {
    # ssh-agent が起動していない場合は起動する
    test -z "$SSH_AUTH_SOCK" && eval "$(ssh-agent)"
}

# : "Setup nodenv" && {
#     type nodenv &>/dev/null && {
#         eval "$(nodenv init - bash)"
#     }
# }

: "Load bash-preexec" && {
    test -f "$HOME/bash-preexec.sh" && . "$HOME/bash-preexec.sh"
}

: "Load .bashrc" && {
    # .bashrc が存在する場合は読み込む
    test -r "$HOME/.bashrc" && . "$HOME/.bashrc"
    # .bashrc.local が存在する場合は読み込む
    test -r "$HOME/.bashrc.local" && . "$HOME/.bashrc.local"
}
