(setq max-lisp-eval-depth 3000)
(setq max-specpdl-size 6000)
(setq initial-scratch-message nil)
(setq inhibit-startup-screen t)
(setq message-log-max t)
(setq comint-scroll-show-maximum-output t)
(setq completion-ignore-case t)
(setq read-file-name-completion-ignore-case t)
(setq kill-whole-line t)
(setq next-line-add-newlines nil)
(setq scroll-conservatively 35)
(setq scroll-margin 0)
(setq scroll-step 1)
(setq visible-bell nil)
(setq ring-bell-function 'ignore)
(setq view-read-only t)
(fset 'yes-or-no-p 'y-or-n-p)
(put 'downcase-region 'disabled nil)
